### ISSUE TITLE
gops crashes on macos without a CLI command on startup

### ISSUE THREAD

**Issue by pcj** [google/gops#153]
```
$ (cd $(mktemp -d); GO111MODULE=on go get github.com/google/gops/@v0.3.21)
```

```
$ ~/go/bin/gops
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x410df6e]

goroutine 11 [running]:
rsc.io/goversion/version.(*machoExe).Symbols(0xc000024210)
	/Users/paul.johnston/go/pkg/mod/rsc.io/goversion@v1.2.0/version/exe.go:290 +0x2e
rsc.io/goversion/version.ReadExe({0xc000024210, 0x0})
	/Users/paul.johnston/go/pkg/mod/rsc.io/goversion@v1.2.0/version/read.go:41 +0x1d0
github.com/google/gops/goprocess.isGo({0x4196550, 0xc00006a4c0})
	/Users/paul.johnston/go/pkg/mod/github.com/google/gops@v0.3.21/goprocess/gp.go:123 +0x93
github.com/google/gops/goprocess.findAll.func1()
	/Users/paul.johnston/go/pkg/mod/github.com/google/gops@v0.3.21/goprocess/gp.go:60 +0xd1
created by github.com/google/gops/goprocess.findAll
	/Users/paul.johnston/go/pkg/mod/github.com/google/gops@v0.3.21/goprocess/gp.go:56 +0xd4
```

```
$ go version
go version go1.17.1 darwin/amd64
```

**Comment by tklauser** [comment]
I think #166 should fix this issue, at least when building `gops` using Go 1.18.

@pcj could you please check whether `gops` v0.3.23 built using Go 1.18 works as expected for you?

**Comment by tklauser** [comment]
Fixed by #166
